# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-12-29 17:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_courseorg_click_nums'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courseorg',
            old_name='num_class',
            new_name='course_num',
        ),
        migrations.AddField(
            model_name='courseorg',
            name='address',
            field=models.TextField(default='example', verbose_name='\u8bfe\u7a0b\u5730\u5740'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='courseorg',
            name='students',
            field=models.IntegerField(default=0, verbose_name='\u5b66\u751f\u6570'),
        ),
    ]
