# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2019-01-07 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_teacher_org'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='image',
            field=models.ImageField(default='', upload_to='teacher/%Y/%M', verbose_name='\u6559\u5e08\u7167\u7247'),
            preserve_default=False,
        ),
    ]
