# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2019-01-09 16:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_auto_20190109_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='tag',
            field=models.CharField(default='', max_length=50, verbose_name='\u6807\u7b7e'),
        ),
    ]
